[package]
name = "nalg-test"
version = "0.1.0"
authors = ["damien <riouxld21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gmm = { path = "../../" }
rand = "*"
statrs = "*"
nalgebra = "*"